# Custom Language File for Launcher Customizer

[ejs.app]
title = "MCSquad Launcher"

[ejs.landing]
mediaGitHubURL = "#"
mediaTwitterURL = "https://twitter.com/salvamecraftx"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/y6HDfuqs7H"

[ejs.settings]
sourceGithubLink = "https://github.com/wally720/MCSquad"
supportLink = "https://github.com/wally720/MCSquad/issues"

[ejs.welcome]
welcomeHeader = "Bienvenido a la MCSquad"
welcomeDescription = "Ac√° encontraras el acceso a los diferentes proyectos o servidores que tenemos preparados para ti."
welcomeDescCTA = "Estas preparado para la aventura?."
